### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when checking say messages

### ISSUE THREAD

**Issue by pmacalpine** [magmaOffenburg/magmaProxy#2]
When running both the 2014 l3m-sim and mithras3d agents the proxy is throwing the following exception:
Exception in thread "Thread-17" java.lang.StringIndexOutOfBoundsException: String index out of range: 238
    at java.lang.String.charAt(String.java:658)
    at magma.tools.SAProxy.impl.AgentProxy$ClientActionsForwarder.checkSay(AgentProxy.java:358)
    at magma.tools.SAProxy.impl.AgentProxy$ClientActionsForwarder.run(AgentProxy.java:309)

I haven't isolated exact messages for which this exception is thrown, however below are example messages from each team:

l3m-sim: (lle1 0.15)(rle1 0.12)(lle2 0.14)(rle2 2.46)(lle3 -2.61)(rle3 4.62)(lle4 -1.27)(rle4 5.65)(lle5 4.01)(rle5 -9.39)(lle6 -0.13)(rle6 -2.46)(he1 0.00) (he2 -4.17)(say -6.0_-2.1)

mithrad3d: (lae1 0)(rae1 0)(lae2 0)(rae2 0)(lae3 0)(rae3 0)(lae4 0)(rae4 0)(lle1 0)(rle1 0)(lle2 0)(rle2 0)(lle3 0)(rle3 -0.347824)(lle4 0)(rle4 0.322004)(lle5 0)(rle5 0)(lle6 0)(rle6 0)(lle7 0)(rle7 0)(he1 -6)(he2 0)(say u11rc03.92947)

**Comment by pmacalpine** [comment]
Perhaps this is happening because both teams' messages end with a say message.
